name: Build EPG
on:
  schedule:
    - cron: '00 06 * * *'
      
env:
  TZ: Asia/Shanghai


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Update epg
      run: |
        python epg.py
        
    - name: commit
      run: |
        git config --global user.email "zhujife@gmail.com"
        git config --global user.name "sam white"
        git add .
        git commit -m "Update epg"
        git push origin master
