name: Build EPG
on:
  schedule:
    - cron: 30 06 * * *
      
env:
  TZ: Asia/Shanghai


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Update epg
      run: |
        python epg.py
        
    - name: commit
      run: |
        git branch newbranch 
        git checkout newbranch
        git config --global user.email "zhujife@gmail.com"
        git config --global user.name "sam white"
        git add .
        git commit -m "Update epg"
        git checkout master 
        git merge newbranch  
        git push -u origin master
        git branch -D newbranch
